// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: log.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RhineSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data          []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Sig           []byte `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Supportedalgo int32  `protobuf:"varint,3,opt,name=Supportedalgo,proto3" json:"Supportedalgo,omitempty"`
	DataPostfix   []byte `protobuf:"bytes,4,opt,name=DataPostfix,proto3" json:"DataPostfix,omitempty"`
}

func (x *RhineSig) Reset() {
	*x = RhineSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RhineSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RhineSig) ProtoMessage() {}

func (x *RhineSig) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RhineSig.ProtoReflect.Descriptor instead.
func (*RhineSig) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *RhineSig) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RhineSig) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *RhineSig) GetSupportedalgo() int32 {
	if x != nil {
		return x.Supportedalgo
	}
	return 0
}

func (x *RhineSig) GetDataPostfix() []byte {
	if x != nil {
		return x.DataPostfix
	}
	return nil
}

type Lwit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesignatedLogs []string `protobuf:"bytes,1,rep,name=DesignatedLogs,proto3" json:"DesignatedLogs,omitempty"`
	Log            string   `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	NdsHash        []byte   `protobuf:"bytes,3,opt,name=NdsHash,proto3" json:"NdsHash,omitempty"`
	Sig            []byte   `protobuf:"bytes,4,opt,name=Sig,proto3" json:"Sig,omitempty"`
}

func (x *Lwit) Reset() {
	*x = Lwit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lwit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lwit) ProtoMessage() {}

func (x *Lwit) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lwit.ProtoReflect.Descriptor instead.
func (*Lwit) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *Lwit) GetDesignatedLogs() []string {
	if x != nil {
		return x.DesignatedLogs
	}
	return nil
}

func (x *Lwit) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *Lwit) GetNdsHash() []byte {
	if x != nil {
		return x.NdsHash
	}
	return nil
}

func (x *Lwit) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Acfm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIdent string `protobuf:"bytes,1,opt,name=AggIdent,proto3" json:"AggIdent,omitempty"`
	NdsHash  []byte `protobuf:"bytes,2,opt,name=NdsHash,proto3" json:"NdsHash,omitempty"`
	DSum     []byte `protobuf:"bytes,3,opt,name=DSum,proto3" json:"DSum,omitempty"`
}

func (x *Acfm) Reset() {
	*x = Acfm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acfm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acfm) ProtoMessage() {}

func (x *Acfm) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acfm.ProtoReflect.Descriptor instead.
func (*Acfm) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{2}
}

func (x *Acfm) GetAggIdent() string {
	if x != nil {
		return x.AggIdent
	}
	return ""
}

func (x *Acfm) GetNdsHash() []byte {
	if x != nil {
		return x.NdsHash
	}
	return nil
}

func (x *Acfm) GetDSum() []byte {
	if x != nil {
		return x.DSum
	}
	return nil
}

type DSProofRetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parentzone string `protobuf:"bytes,1,opt,name=Parentzone,proto3" json:"Parentzone,omitempty"`
	Childzone  string `protobuf:"bytes,2,opt,name=Childzone,proto3" json:"Childzone,omitempty"`
}

func (x *DSProofRetRequest) Reset() {
	*x = DSProofRetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSProofRetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSProofRetRequest) ProtoMessage() {}

func (x *DSProofRetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSProofRetRequest.ProtoReflect.Descriptor instead.
func (*DSProofRetRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{3}
}

func (x *DSProofRetRequest) GetParentzone() string {
	if x != nil {
		return x.Parentzone
	}
	return ""
}

func (x *DSProofRetRequest) GetChildzone() string {
	if x != nil {
		return x.Childzone
	}
	return ""
}

type DSProofRetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DSPBytes []byte `protobuf:"bytes,1,opt,name=DSPBytes,proto3" json:"DSPBytes,omitempty"`
}

func (x *DSProofRetResponse) Reset() {
	*x = DSProofRetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSProofRetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSProofRetResponse) ProtoMessage() {}

func (x *DSProofRetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSProofRetResponse.ProtoReflect.Descriptor instead.
func (*DSProofRetResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{4}
}

func (x *DSProofRetResponse) GetDSPBytes() []byte {
	if x != nil {
		return x.DSPBytes
	}
	return nil
}

type DemandLoggingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acsr        *RhineSig `protobuf:"bytes,1,opt,name=Acsr,proto3" json:"Acsr,omitempty"`
	ParentRcert []byte    `protobuf:"bytes,2,opt,name=ParentRcert,proto3" json:"ParentRcert,omitempty"`
	ChildPreRC  []byte    `protobuf:"bytes,3,opt,name=ChildPreRC,proto3" json:"ChildPreRC,omitempty"`
	Nds         []byte    `protobuf:"bytes,4,opt,name=Nds,proto3" json:"Nds,omitempty"`
	Rid         []byte    `protobuf:"bytes,5,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *DemandLoggingRequest) Reset() {
	*x = DemandLoggingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemandLoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandLoggingRequest) ProtoMessage() {}

func (x *DemandLoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandLoggingRequest.ProtoReflect.Descriptor instead.
func (*DemandLoggingRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{5}
}

func (x *DemandLoggingRequest) GetAcsr() *RhineSig {
	if x != nil {
		return x.Acsr
	}
	return nil
}

func (x *DemandLoggingRequest) GetParentRcert() []byte {
	if x != nil {
		return x.ParentRcert
	}
	return nil
}

func (x *DemandLoggingRequest) GetChildPreRC() []byte {
	if x != nil {
		return x.ChildPreRC
	}
	return nil
}

func (x *DemandLoggingRequest) GetNds() []byte {
	if x != nil {
		return x.Nds
	}
	return nil
}

func (x *DemandLoggingRequest) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

type DemandLoggingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogWitness *Lwit  `protobuf:"bytes,1,opt,name=LogWitness,proto3" json:"LogWitness,omitempty"`
	Rid        []byte `protobuf:"bytes,2,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *DemandLoggingResponse) Reset() {
	*x = DemandLoggingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemandLoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandLoggingResponse) ProtoMessage() {}

func (x *DemandLoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandLoggingResponse.ProtoReflect.Descriptor instead.
func (*DemandLoggingResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{6}
}

func (x *DemandLoggingResponse) GetLogWitness() *Lwit {
	if x != nil {
		return x.LogWitness
	}
	return nil
}

func (x *DemandLoggingResponse) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

type SubmitACFMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acfms [][]byte `protobuf:"bytes,1,rep,name=Acfms,proto3" json:"Acfms,omitempty"`
	Rid   []byte   `protobuf:"bytes,2,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *SubmitACFMRequest) Reset() {
	*x = SubmitACFMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitACFMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitACFMRequest) ProtoMessage() {}

func (x *SubmitACFMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitACFMRequest.ProtoReflect.Descriptor instead.
func (*SubmitACFMRequest) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitACFMRequest) GetAcfms() [][]byte {
	if x != nil {
		return x.Acfms
	}
	return nil
}

func (x *SubmitACFMRequest) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

type SubmitACFMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lcfm []byte `protobuf:"bytes,1,opt,name=Lcfm,proto3" json:"Lcfm,omitempty"`
	SCT  []byte `protobuf:"bytes,2,opt,name=SCT,proto3" json:"SCT,omitempty"`
	Rid  []byte `protobuf:"bytes,3,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *SubmitACFMResponse) Reset() {
	*x = SubmitACFMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitACFMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitACFMResponse) ProtoMessage() {}

func (x *SubmitACFMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitACFMResponse.ProtoReflect.Descriptor instead.
func (*SubmitACFMResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitACFMResponse) GetLcfm() []byte {
	if x != nil {
		return x.Lcfm
	}
	return nil
}

func (x *SubmitACFMResponse) GetSCT() []byte {
	if x != nil {
		return x.SCT
	}
	return nil
}

func (x *SubmitACFMResponse) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

var File_log_proto protoreflect.FileDescriptor

var file_log_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x68, 0x69,
	0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x22, 0x78, 0x0a, 0x08, 0x52, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x73, 0x74, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x73, 0x74, 0x66, 0x69, 0x78, 0x22,
	0x6c, 0x0a, 0x04, 0x4c, 0x77, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x53,
	0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x22, 0x50, 0x0a,
	0x04, 0x41, 0x63, 0x66, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x67, 0x67, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x67, 0x67, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x53, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x53, 0x75, 0x6d, 0x22,
	0x51, 0x0a, 0x11, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x7a, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x7a, 0x6f,
	0x6e, 0x65, 0x22, 0x30, 0x0a, 0x12, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x53, 0x50, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x44, 0x53, 0x50, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x4c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x04, 0x41, 0x63, 0x73, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x68,
	0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x52, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x69, 0x67, 0x52,
	0x04, 0x41, 0x63, 0x73, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x52, 0x63, 0x65, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x69, 0x6c, 0x64,
	0x50, 0x72, 0x65, 0x52, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x50, 0x72, 0x65, 0x52, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4e, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x15, 0x44,
	0x65, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x57, 0x69, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x68, 0x69, 0x6e, 0x65,
	0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x77, 0x69, 0x74, 0x52, 0x0a, 0x4c, 0x6f, 0x67, 0x57, 0x69, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x52, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x41, 0x43, 0x46, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41,
	0x63, 0x66, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x41, 0x63, 0x66, 0x6d,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x52, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x43, 0x46,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x63, 0x66,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x4c, 0x63, 0x66, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x43, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x43, 0x54, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x69,
	0x64, 0x32, 0xf6, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x49, 0x0a, 0x0a, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x74, 0x12, 0x1b,
	0x2e, 0x72, 0x68, 0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x68,
	0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x44,
	0x65, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x72,
	0x68, 0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72,
	0x68, 0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x43, 0x46, 0x4d, 0x12, 0x1b, 0x2e,
	0x72, 0x68, 0x69, 0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41,
	0x43, 0x46, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x68, 0x69,
	0x6e, 0x65, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x43, 0x46, 0x4d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x74,
	0x65, 0x61, 0x6d, 0x2f, 0x52, 0x48, 0x49, 0x4e, 0x45, 0x2d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x75, 0x74, 0x68, 0x2f,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData = file_log_proto_rawDesc
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_proto_rawDescData)
	})
	return file_log_proto_rawDescData
}

var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_log_proto_goTypes = []interface{}{
	(*RhineSig)(nil),              // 0: rhinelog.RhineSig
	(*Lwit)(nil),                  // 1: rhinelog.Lwit
	(*Acfm)(nil),                  // 2: rhinelog.Acfm
	(*DSProofRetRequest)(nil),     // 3: rhinelog.DSProofRetRequest
	(*DSProofRetResponse)(nil),    // 4: rhinelog.DSProofRetResponse
	(*DemandLoggingRequest)(nil),  // 5: rhinelog.DemandLoggingRequest
	(*DemandLoggingResponse)(nil), // 6: rhinelog.DemandLoggingResponse
	(*SubmitACFMRequest)(nil),     // 7: rhinelog.SubmitACFMRequest
	(*SubmitACFMResponse)(nil),    // 8: rhinelog.SubmitACFMResponse
}
var file_log_proto_depIdxs = []int32{
	0, // 0: rhinelog.DemandLoggingRequest.Acsr:type_name -> rhinelog.RhineSig
	1, // 1: rhinelog.DemandLoggingResponse.LogWitness:type_name -> rhinelog.Lwit
	3, // 2: rhinelog.LogService.DSProofRet:input_type -> rhinelog.DSProofRetRequest
	5, // 3: rhinelog.LogService.DemandLogging:input_type -> rhinelog.DemandLoggingRequest
	7, // 4: rhinelog.LogService.SubmitACFM:input_type -> rhinelog.SubmitACFMRequest
	4, // 5: rhinelog.LogService.DSProofRet:output_type -> rhinelog.DSProofRetResponse
	6, // 6: rhinelog.LogService.DemandLogging:output_type -> rhinelog.DemandLoggingResponse
	8, // 7: rhinelog.LogService.SubmitACFM:output_type -> rhinelog.SubmitACFMResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RhineSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lwit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Acfm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSProofRetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSProofRetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemandLoggingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemandLoggingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitACFMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitACFMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_rawDesc = nil
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
