// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: log.proto

package log

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	DSProofRet(ctx context.Context, in *DSProofRetRequest, opts ...grpc.CallOption) (*DSProofRetResponse, error)
	DemandLogging(ctx context.Context, in *DemandLoggingRequest, opts ...grpc.CallOption) (*DemandLoggingResponse, error)
	SubmitACFM(ctx context.Context, in *SubmitACFMRequest, opts ...grpc.CallOption) (*SubmitACFMResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) DSProofRet(ctx context.Context, in *DSProofRetRequest, opts ...grpc.CallOption) (*DSProofRetResponse, error) {
	out := new(DSProofRetResponse)
	err := c.cc.Invoke(ctx, "/rhinelog.LogService/DSProofRet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) DemandLogging(ctx context.Context, in *DemandLoggingRequest, opts ...grpc.CallOption) (*DemandLoggingResponse, error) {
	out := new(DemandLoggingResponse)
	err := c.cc.Invoke(ctx, "/rhinelog.LogService/DemandLogging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SubmitACFM(ctx context.Context, in *SubmitACFMRequest, opts ...grpc.CallOption) (*SubmitACFMResponse, error) {
	out := new(SubmitACFMResponse)
	err := c.cc.Invoke(ctx, "/rhinelog.LogService/SubmitACFM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility
type LogServiceServer interface {
	DSProofRet(context.Context, *DSProofRetRequest) (*DSProofRetResponse, error)
	DemandLogging(context.Context, *DemandLoggingRequest) (*DemandLoggingResponse, error)
	SubmitACFM(context.Context, *SubmitACFMRequest) (*SubmitACFMResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (UnimplementedLogServiceServer) DSProofRet(context.Context, *DSProofRetRequest) (*DSProofRetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DSProofRet not implemented")
}
func (UnimplementedLogServiceServer) DemandLogging(context.Context, *DemandLoggingRequest) (*DemandLoggingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemandLogging not implemented")
}
func (UnimplementedLogServiceServer) SubmitACFM(context.Context, *SubmitACFMRequest) (*SubmitACFMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitACFM not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_DSProofRet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DSProofRetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DSProofRet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rhinelog.LogService/DSProofRet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DSProofRet(ctx, req.(*DSProofRetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_DemandLogging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemandLoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DemandLogging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rhinelog.LogService/DemandLogging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DemandLogging(ctx, req.(*DemandLoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SubmitACFM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitACFMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SubmitACFM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rhinelog.LogService/SubmitACFM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SubmitACFM(ctx, req.(*SubmitACFMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rhinelog.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DSProofRet",
			Handler:    _LogService_DSProofRet_Handler,
		},
		{
			MethodName: "DemandLogging",
			Handler:    _LogService_DemandLogging_Handler,
		},
		{
			MethodName: "SubmitACFM",
			Handler:    _LogService_SubmitACFM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
