// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: aggregator.proto

package aggregator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartLogresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumR string `protobuf:"bytes,1,opt,name=NumR,proto3" json:"NumR,omitempty"`
}

func (x *StartLogresRequest) Reset() {
	*x = StartLogresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLogresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLogresRequest) ProtoMessage() {}

func (x *StartLogresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLogresRequest.ProtoReflect.Descriptor instead.
func (*StartLogresRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *StartLogresRequest) GetNumR() string {
	if x != nil {
		return x.NumR
	}
	return ""
}

type StartLogresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=Res,proto3" json:"Res,omitempty"`
}

func (x *StartLogresResponse) Reset() {
	*x = StartLogresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLogresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLogresResponse) ProtoMessage() {}

func (x *StartLogresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLogresResponse.ProtoReflect.Descriptor instead.
func (*StartLogresResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *StartLogresResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type LogresValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []byte `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *LogresValueRequest) Reset() {
	*x = LogresValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogresValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogresValueRequest) ProtoMessage() {}

func (x *LogresValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogresValueRequest.ProtoReflect.Descriptor instead.
func (*LogresValueRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *LogresValueRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type LogresValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=Res,proto3" json:"Res,omitempty"`
}

func (x *LogresValueResponse) Reset() {
	*x = LogresValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogresValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogresValueResponse) ProtoMessage() {}

func (x *LogresValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogresValueResponse.ProtoReflect.Descriptor instead.
func (*LogresValueResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *LogresValueResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type PreLoggingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prl []byte `protobuf:"bytes,1,opt,name=Prl,proto3" json:"Prl,omitempty"`
}

func (x *PreLoggingRequest) Reset() {
	*x = PreLoggingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreLoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreLoggingRequest) ProtoMessage() {}

func (x *PreLoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreLoggingRequest.ProtoReflect.Descriptor instead.
func (*PreLoggingRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{4}
}

func (x *PreLoggingRequest) GetPrl() []byte {
	if x != nil {
		return x.Prl
	}
	return nil
}

type PreLoggingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Att []byte `protobuf:"bytes,1,opt,name=Att,proto3" json:"Att,omitempty"`
}

func (x *PreLoggingResponse) Reset() {
	*x = PreLoggingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreLoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreLoggingResponse) ProtoMessage() {}

func (x *PreLoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreLoggingResponse.ProtoReflect.Descriptor instead.
func (*PreLoggingResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{5}
}

func (x *PreLoggingResponse) GetAtt() []byte {
	if x != nil {
		return x.Att
	}
	return nil
}

type LoggingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lreq []byte `protobuf:"bytes,1,opt,name=Lreq,proto3" json:"Lreq,omitempty"`
}

func (x *LoggingRequest) Reset() {
	*x = LoggingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingRequest) ProtoMessage() {}

func (x *LoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingRequest.ProtoReflect.Descriptor instead.
func (*LoggingRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{6}
}

func (x *LoggingRequest) GetLreq() []byte {
	if x != nil {
		return x.Lreq
	}
	return nil
}

type LoggingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogConf []byte `protobuf:"bytes,1,opt,name=LogConf,proto3" json:"LogConf,omitempty"`
}

func (x *LoggingResponse) Reset() {
	*x = LoggingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingResponse) ProtoMessage() {}

func (x *LoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingResponse.ProtoReflect.Descriptor instead.
func (*LoggingResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{7}
}

func (x *LoggingResponse) GetLogConf() []byte {
	if x != nil {
		return x.LogConf
	}
	return nil
}

type DSProofRetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parentzone string `protobuf:"bytes,1,opt,name=Parentzone,proto3" json:"Parentzone,omitempty"`
	Childzone  string `protobuf:"bytes,2,opt,name=Childzone,proto3" json:"Childzone,omitempty"`
}

func (x *DSProofRetRequest) Reset() {
	*x = DSProofRetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSProofRetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSProofRetRequest) ProtoMessage() {}

func (x *DSProofRetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSProofRetRequest.ProtoReflect.Descriptor instead.
func (*DSProofRetRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{8}
}

func (x *DSProofRetRequest) GetParentzone() string {
	if x != nil {
		return x.Parentzone
	}
	return ""
}

func (x *DSProofRetRequest) GetChildzone() string {
	if x != nil {
		return x.Childzone
	}
	return ""
}

type DSProofRetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DSPBytes []byte `protobuf:"bytes,1,opt,name=DSPBytes,proto3" json:"DSPBytes,omitempty"`
}

func (x *DSProofRetResponse) Reset() {
	*x = DSProofRetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSProofRetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSProofRetResponse) ProtoMessage() {}

func (x *DSProofRetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSProofRetResponse.ProtoReflect.Descriptor instead.
func (*DSProofRetResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{9}
}

func (x *DSProofRetResponse) GetDSPBytes() []byte {
	if x != nil {
		return x.DSPBytes
	}
	return nil
}

type Lwit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesignatedLogs []string `protobuf:"bytes,1,rep,name=DesignatedLogs,proto3" json:"DesignatedLogs,omitempty"`
	Log            string   `protobuf:"bytes,2,opt,name=Log,proto3" json:"Log,omitempty"`
	NdsHash        []byte   `protobuf:"bytes,3,opt,name=NdsHash,proto3" json:"NdsHash,omitempty"`
	Sig            []byte   `protobuf:"bytes,4,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Data           []byte   `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Lwit) Reset() {
	*x = Lwit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lwit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lwit) ProtoMessage() {}

func (x *Lwit) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lwit.ProtoReflect.Descriptor instead.
func (*Lwit) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{10}
}

func (x *Lwit) GetDesignatedLogs() []string {
	if x != nil {
		return x.DesignatedLogs
	}
	return nil
}

func (x *Lwit) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *Lwit) GetNdsHash() []byte {
	if x != nil {
		return x.NdsHash
	}
	return nil
}

func (x *Lwit) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Lwit) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Acfm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIdent string `protobuf:"bytes,1,opt,name=AggIdent,proto3" json:"AggIdent,omitempty"`
	NdsHash  []byte `protobuf:"bytes,2,opt,name=NdsHash,proto3" json:"NdsHash,omitempty"`
	DSum     []byte `protobuf:"bytes,3,opt,name=DSum,proto3" json:"DSum,omitempty"`
}

func (x *Acfm) Reset() {
	*x = Acfm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acfm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acfm) ProtoMessage() {}

func (x *Acfm) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acfm.ProtoReflect.Descriptor instead.
func (*Acfm) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{11}
}

func (x *Acfm) GetAggIdent() string {
	if x != nil {
		return x.AggIdent
	}
	return ""
}

func (x *Acfm) GetNdsHash() []byte {
	if x != nil {
		return x.NdsHash
	}
	return nil
}

func (x *Acfm) GetDSum() []byte {
	if x != nil {
		return x.DSum
	}
	return nil
}

type RetrieveDSALogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedZones []string `protobuf:"bytes,1,rep,name=RequestedZones,proto3" json:"RequestedZones,omitempty"`
}

func (x *RetrieveDSALogRequest) Reset() {
	*x = RetrieveDSALogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveDSALogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDSALogRequest) ProtoMessage() {}

func (x *RetrieveDSALogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDSALogRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDSALogRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{12}
}

func (x *RetrieveDSALogRequest) GetRequestedZones() []string {
	if x != nil {
		return x.RequestedZones
	}
	return nil
}

type RetrieveDSALogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DSAPayload    [][]byte `protobuf:"bytes,1,rep,name=DSAPayload,proto3" json:"DSAPayload,omitempty"`
	DSASignatures [][]byte `protobuf:"bytes,2,rep,name=DSASignatures,proto3" json:"DSASignatures,omitempty"`
}

func (x *RetrieveDSALogResponse) Reset() {
	*x = RetrieveDSALogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveDSALogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDSALogResponse) ProtoMessage() {}

func (x *RetrieveDSALogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDSALogResponse.ProtoReflect.Descriptor instead.
func (*RetrieveDSALogResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{13}
}

func (x *RetrieveDSALogResponse) GetDSAPayload() [][]byte {
	if x != nil {
		return x.DSAPayload
	}
	return nil
}

func (x *RetrieveDSALogResponse) GetDSASignatures() [][]byte {
	if x != nil {
		return x.DSASignatures
	}
	return nil
}

type SubmitNDSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nds           []byte  `protobuf:"bytes,1,opt,name=Nds,proto3" json:"Nds,omitempty"`
	Lwits         []*Lwit `protobuf:"bytes,2,rep,name=Lwits,proto3" json:"Lwits,omitempty"`
	Rid           []byte  `protobuf:"bytes,3,opt,name=Rid,proto3" json:"Rid,omitempty"`
	Rcertp        []byte  `protobuf:"bytes,4,opt,name=Rcertp,proto3" json:"Rcertp,omitempty"`
	Acsrpayload   []byte  `protobuf:"bytes,5,opt,name=Acsrpayload,proto3" json:"Acsrpayload,omitempty"`
	Acsrsignature []byte  `protobuf:"bytes,6,opt,name=Acsrsignature,proto3" json:"Acsrsignature,omitempty"`
}

func (x *SubmitNDSRequest) Reset() {
	*x = SubmitNDSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitNDSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitNDSRequest) ProtoMessage() {}

func (x *SubmitNDSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitNDSRequest.ProtoReflect.Descriptor instead.
func (*SubmitNDSRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitNDSRequest) GetNds() []byte {
	if x != nil {
		return x.Nds
	}
	return nil
}

func (x *SubmitNDSRequest) GetLwits() []*Lwit {
	if x != nil {
		return x.Lwits
	}
	return nil
}

func (x *SubmitNDSRequest) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

func (x *SubmitNDSRequest) GetRcertp() []byte {
	if x != nil {
		return x.Rcertp
	}
	return nil
}

func (x *SubmitNDSRequest) GetAcsrpayload() []byte {
	if x != nil {
		return x.Acsrpayload
	}
	return nil
}

func (x *SubmitNDSRequest) GetAcsrsignature() []byte {
	if x != nil {
		return x.Acsrsignature
	}
	return nil
}

type SubmitNDSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acfmg []byte `protobuf:"bytes,1,opt,name=Acfmg,proto3" json:"Acfmg,omitempty"`
	Rid   []byte `protobuf:"bytes,2,opt,name=Rid,proto3" json:"Rid,omitempty"`
}

func (x *SubmitNDSResponse) Reset() {
	*x = SubmitNDSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitNDSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitNDSResponse) ProtoMessage() {}

func (x *SubmitNDSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitNDSResponse.ProtoReflect.Descriptor instead.
func (*SubmitNDSResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitNDSResponse) GetAcfmg() []byte {
	if x != nil {
		return x.Acfmg
	}
	return nil
}

func (x *SubmitNDSResponse) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

var File_aggregator_proto protoreflect.FileDescriptor

var file_aggregator_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x28,
	0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x52, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x52, 0x22, 0x27, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52, 0x65,
	0x73, 0x22, 0x26, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x27, 0x0a, 0x13, 0x4c, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x52,
	0x65, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x50, 0x72, 0x6c, 0x22, 0x26, 0x0a, 0x12, 0x50, 0x72, 0x65,
	0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x41, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x41, 0x74,
	0x74, 0x22, 0x24, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x4c, 0x72, 0x65, 0x71, 0x22, 0x2b, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x67, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f,
	0x67, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4c, 0x6f, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x22, 0x51, 0x0a, 0x11, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68,
	0x69, 0x6c, 0x64, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x30, 0x0a, 0x12, 0x44, 0x53, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x53, 0x50, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x44, 0x53, 0x50, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x4c, 0x77,
	0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x65, 0x64,
	0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4e,
	0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x04,
	0x41, 0x63, 0x66, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x67, 0x67, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x67, 0x67, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x4e, 0x64, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x53,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x53, 0x75, 0x6d, 0x22, 0x3f,
	0x0a, 0x15, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x53, 0x41, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x22,
	0x5e, 0x0a, 0x16, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x53, 0x41, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x53, 0x41,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x44,
	0x53, 0x41, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x0d, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22,
	0xbe, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4e, 0x44, 0x53, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x4e, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x4c, 0x77, 0x69, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x4c, 0x77, 0x69, 0x74, 0x52, 0x05, 0x4c, 0x77, 0x69, 0x74, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x63, 0x65, 0x72, 0x74, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x52, 0x63, 0x65, 0x72, 0x74, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x73, 0x72,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x41,
	0x63, 0x73, 0x72, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x63,
	0x73, 0x72, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x41, 0x63, 0x73, 0x72, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x3b, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4e, 0x44, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x63, 0x66, 0x6d, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x41, 0x63, 0x66, 0x6d, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x69, 0x64, 0x32, 0xb8, 0x04,
	0x0a, 0x0a, 0x41, 0x67, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0b,
	0x44, 0x53, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x61, 0x6c, 0x12, 0x21, 0x2e, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x44, 0x53, 0x41, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x44, 0x53, 0x41, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4e, 0x44,
	0x53, 0x12, 0x1c, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x4e, 0x44, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x4e, 0x44, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x1d,
	0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x4c,
	0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x4c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x61, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x44, 0x53, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x74, 0x65, 0x61,
	0x6d, 0x2f, 0x52, 0x48, 0x49, 0x4e, 0x45, 0x2d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x75, 0x74, 0x68, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggregator_proto_rawDescOnce sync.Once
	file_aggregator_proto_rawDescData = file_aggregator_proto_rawDesc
)

func file_aggregator_proto_rawDescGZIP() []byte {
	file_aggregator_proto_rawDescOnce.Do(func() {
		file_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregator_proto_rawDescData)
	})
	return file_aggregator_proto_rawDescData
}

var file_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_aggregator_proto_goTypes = []interface{}{
	(*StartLogresRequest)(nil),     // 0: aggregator.StartLogresRequest
	(*StartLogresResponse)(nil),    // 1: aggregator.StartLogresResponse
	(*LogresValueRequest)(nil),     // 2: aggregator.LogresValueRequest
	(*LogresValueResponse)(nil),    // 3: aggregator.LogresValueResponse
	(*PreLoggingRequest)(nil),      // 4: aggregator.PreLoggingRequest
	(*PreLoggingResponse)(nil),     // 5: aggregator.PreLoggingResponse
	(*LoggingRequest)(nil),         // 6: aggregator.LoggingRequest
	(*LoggingResponse)(nil),        // 7: aggregator.LoggingResponse
	(*DSProofRetRequest)(nil),      // 8: aggregator.DSProofRetRequest
	(*DSProofRetResponse)(nil),     // 9: aggregator.DSProofRetResponse
	(*Lwit)(nil),                   // 10: aggregator.Lwit
	(*Acfm)(nil),                   // 11: aggregator.Acfm
	(*RetrieveDSALogRequest)(nil),  // 12: aggregator.RetrieveDSALogRequest
	(*RetrieveDSALogResponse)(nil), // 13: aggregator.RetrieveDSALogResponse
	(*SubmitNDSRequest)(nil),       // 14: aggregator.SubmitNDSRequest
	(*SubmitNDSResponse)(nil),      // 15: aggregator.SubmitNDSResponse
}
var file_aggregator_proto_depIdxs = []int32{
	10, // 0: aggregator.SubmitNDSRequest.Lwits:type_name -> aggregator.Lwit
	12, // 1: aggregator.AggService.DSRetrieval:input_type -> aggregator.RetrieveDSALogRequest
	14, // 2: aggregator.AggService.SubmitNDS:input_type -> aggregator.SubmitNDSRequest
	4,  // 3: aggregator.AggService.PreLogging:input_type -> aggregator.PreLoggingRequest
	6,  // 4: aggregator.AggService.Logging:input_type -> aggregator.LoggingRequest
	8,  // 5: aggregator.AggService.DSProofRet:input_type -> aggregator.DSProofRetRequest
	0,  // 6: aggregator.AggService.StartLogres:input_type -> aggregator.StartLogresRequest
	2,  // 7: aggregator.AggService.LogresValue:input_type -> aggregator.LogresValueRequest
	13, // 8: aggregator.AggService.DSRetrieval:output_type -> aggregator.RetrieveDSALogResponse
	15, // 9: aggregator.AggService.SubmitNDS:output_type -> aggregator.SubmitNDSResponse
	5,  // 10: aggregator.AggService.PreLogging:output_type -> aggregator.PreLoggingResponse
	7,  // 11: aggregator.AggService.Logging:output_type -> aggregator.LoggingResponse
	9,  // 12: aggregator.AggService.DSProofRet:output_type -> aggregator.DSProofRetResponse
	1,  // 13: aggregator.AggService.StartLogres:output_type -> aggregator.StartLogresResponse
	3,  // 14: aggregator.AggService.LogresValue:output_type -> aggregator.LogresValueResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_aggregator_proto_init() }
func file_aggregator_proto_init() {
	if File_aggregator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggregator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLogresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLogresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogresValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogresValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreLoggingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreLoggingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoggingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoggingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSProofRetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSProofRetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lwit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Acfm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveDSALogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveDSALogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitNDSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitNDSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_proto_goTypes,
		DependencyIndexes: file_aggregator_proto_depIdxs,
		MessageInfos:      file_aggregator_proto_msgTypes,
	}.Build()
	File_aggregator_proto = out.File
	file_aggregator_proto_rawDesc = nil
	file_aggregator_proto_goTypes = nil
	file_aggregator_proto_depIdxs = nil
}
