// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: aggregator.proto

package aggregator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AggServiceClient is the client API for AggService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggServiceClient interface {
	DSRetrieval(ctx context.Context, in *RetrieveDSALogRequest, opts ...grpc.CallOption) (*RetrieveDSALogResponse, error)
	SubmitNDS(ctx context.Context, in *SubmitNDSRequest, opts ...grpc.CallOption) (*SubmitNDSResponse, error)
	PreLogging(ctx context.Context, in *PreLoggingRequest, opts ...grpc.CallOption) (*PreLoggingResponse, error)
	Logging(ctx context.Context, in *LoggingRequest, opts ...grpc.CallOption) (*LoggingResponse, error)
	DSProofRet(ctx context.Context, in *DSProofRetRequest, opts ...grpc.CallOption) (*DSProofRetResponse, error)
	StartLogres(ctx context.Context, in *StartLogresRequest, opts ...grpc.CallOption) (*StartLogresResponse, error)
	LogresValue(ctx context.Context, in *LogresValueRequest, opts ...grpc.CallOption) (*LogresValueResponse, error)
}

type aggServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggServiceClient(cc grpc.ClientConnInterface) AggServiceClient {
	return &aggServiceClient{cc}
}

func (c *aggServiceClient) DSRetrieval(ctx context.Context, in *RetrieveDSALogRequest, opts ...grpc.CallOption) (*RetrieveDSALogResponse, error) {
	out := new(RetrieveDSALogResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/DSRetrieval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) SubmitNDS(ctx context.Context, in *SubmitNDSRequest, opts ...grpc.CallOption) (*SubmitNDSResponse, error) {
	out := new(SubmitNDSResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/SubmitNDS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) PreLogging(ctx context.Context, in *PreLoggingRequest, opts ...grpc.CallOption) (*PreLoggingResponse, error) {
	out := new(PreLoggingResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/PreLogging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) Logging(ctx context.Context, in *LoggingRequest, opts ...grpc.CallOption) (*LoggingResponse, error) {
	out := new(LoggingResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/Logging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) DSProofRet(ctx context.Context, in *DSProofRetRequest, opts ...grpc.CallOption) (*DSProofRetResponse, error) {
	out := new(DSProofRetResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/DSProofRet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) StartLogres(ctx context.Context, in *StartLogresRequest, opts ...grpc.CallOption) (*StartLogresResponse, error) {
	out := new(StartLogresResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/StartLogres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggServiceClient) LogresValue(ctx context.Context, in *LogresValueRequest, opts ...grpc.CallOption) (*LogresValueResponse, error) {
	out := new(LogresValueResponse)
	err := c.cc.Invoke(ctx, "/aggregator.AggService/LogresValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggServiceServer is the server API for AggService service.
// All implementations must embed UnimplementedAggServiceServer
// for forward compatibility
type AggServiceServer interface {
	DSRetrieval(context.Context, *RetrieveDSALogRequest) (*RetrieveDSALogResponse, error)
	SubmitNDS(context.Context, *SubmitNDSRequest) (*SubmitNDSResponse, error)
	PreLogging(context.Context, *PreLoggingRequest) (*PreLoggingResponse, error)
	Logging(context.Context, *LoggingRequest) (*LoggingResponse, error)
	DSProofRet(context.Context, *DSProofRetRequest) (*DSProofRetResponse, error)
	StartLogres(context.Context, *StartLogresRequest) (*StartLogresResponse, error)
	LogresValue(context.Context, *LogresValueRequest) (*LogresValueResponse, error)
	mustEmbedUnimplementedAggServiceServer()
}

// UnimplementedAggServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAggServiceServer struct {
}

func (UnimplementedAggServiceServer) DSRetrieval(context.Context, *RetrieveDSALogRequest) (*RetrieveDSALogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DSRetrieval not implemented")
}
func (UnimplementedAggServiceServer) SubmitNDS(context.Context, *SubmitNDSRequest) (*SubmitNDSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitNDS not implemented")
}
func (UnimplementedAggServiceServer) PreLogging(context.Context, *PreLoggingRequest) (*PreLoggingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreLogging not implemented")
}
func (UnimplementedAggServiceServer) Logging(context.Context, *LoggingRequest) (*LoggingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logging not implemented")
}
func (UnimplementedAggServiceServer) DSProofRet(context.Context, *DSProofRetRequest) (*DSProofRetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DSProofRet not implemented")
}
func (UnimplementedAggServiceServer) StartLogres(context.Context, *StartLogresRequest) (*StartLogresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLogres not implemented")
}
func (UnimplementedAggServiceServer) LogresValue(context.Context, *LogresValueRequest) (*LogresValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogresValue not implemented")
}
func (UnimplementedAggServiceServer) mustEmbedUnimplementedAggServiceServer() {}

// UnsafeAggServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggServiceServer will
// result in compilation errors.
type UnsafeAggServiceServer interface {
	mustEmbedUnimplementedAggServiceServer()
}

func RegisterAggServiceServer(s grpc.ServiceRegistrar, srv AggServiceServer) {
	s.RegisterService(&AggService_ServiceDesc, srv)
}

func _AggService_DSRetrieval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDSALogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).DSRetrieval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/DSRetrieval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).DSRetrieval(ctx, req.(*RetrieveDSALogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_SubmitNDS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitNDSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).SubmitNDS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/SubmitNDS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).SubmitNDS(ctx, req.(*SubmitNDSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_PreLogging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreLoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).PreLogging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/PreLogging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).PreLogging(ctx, req.(*PreLoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_Logging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).Logging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/Logging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).Logging(ctx, req.(*LoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_DSProofRet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DSProofRetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).DSProofRet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/DSProofRet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).DSProofRet(ctx, req.(*DSProofRetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_StartLogres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLogresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).StartLogres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/StartLogres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).StartLogres(ctx, req.(*StartLogresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggService_LogresValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogresValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggServiceServer).LogresValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aggregator.AggService/LogresValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggServiceServer).LogresValue(ctx, req.(*LogresValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggService_ServiceDesc is the grpc.ServiceDesc for AggService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.AggService",
	HandlerType: (*AggServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DSRetrieval",
			Handler:    _AggService_DSRetrieval_Handler,
		},
		{
			MethodName: "SubmitNDS",
			Handler:    _AggService_SubmitNDS_Handler,
		},
		{
			MethodName: "PreLogging",
			Handler:    _AggService_PreLogging_Handler,
		},
		{
			MethodName: "Logging",
			Handler:    _AggService_Logging_Handler,
		},
		{
			MethodName: "DSProofRet",
			Handler:    _AggService_DSProofRet_Handler,
		},
		{
			MethodName: "StartLogres",
			Handler:    _AggService_StartLogres_Handler,
		},
		{
			MethodName: "LogresValue",
			Handler:    _AggService_LogresValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregator.proto",
}
